- name: Edge Configuration
  template: src=/var/lib/jenkins/workspace/Lab11PoC@2/ANSIBLE/roles/core/templates/core.j2 dest=/var/lib/jenkins/workspace/Lab11PoC@2/ANSIBLE/CFGS/{{ item.hostname }}.txt
  with_items: "{{ coreConfig }}"
