- name: Server Configuration
  template: src=/var/lib/jenkins/workspace/Lab11PoC@2/ANSIBLE/roles/server/templates/server.j2 dest=/var/lib/jenkins/workspace/Lab11PoC@2/ANSIBLE/CFGS/{{ item.hostname }}.txt
  with_items: "{{ serverConfig }}"
